---
title: "Weight Projector"
output: html_document
editor_options:
  chunk_output_type: console
---
<!-- Based on https://stackoverflow.com/questions/71353287/user-inputs-for-r-ggplot-or-plotly-without-shiny/71363657#71363657 -->

<!-- Include plolty.js script -->
<script src="https://cdn.plot.ly/plotly-2.31.1.min.js" charset="utf-8"></script>

<!-- Include DataTables script -->
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.dataTables.min.css">

<!-- Include DataTables ColReorder -->
<script src="https://cdn.datatables.net/colreorder/2.0.1/js/dataTables.colReorder.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/colreorder/2.0.1/css/colReorder.dataTables.min.css">

<!-- Include DataTables Responsive -->
<script src="https://cdn.datatables.net/responsive/3.0.2/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/3.0.2/js/responsive.dataTables.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.2/css/responsive.dataTables.min.css">

<!-- Include DataTables ColVis -->
<script src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js"></script>
<script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.colVis.min.js"></script>
<script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.dataTables.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/3.0.2/css/buttons.dataTables.css">


<!-- This is a container for your inputs -->

:::{.input-container}

<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  <b>REMINDER!</b> This is only an estimate to help build your eating plan. 
  Consult a healthcare professional before changing your routine and 
  if you experience any weird symptoms (e.g., palpitations, dizziness)! 
  There are a lot of factors that can influence BMR/TDEE (e.g., stress, 
  exercise, sleep, health conditions), so reassess your strategy every few weeks.
  BMI is not the only metric of health, and reaching a "healthy weight" may not 
  be ideal based on individual factors (again, talk to healthcare provider).
  Generally, estrogen-dominant people should stay above 1200 calories, and 
  testosterone-dominant people should stay above 1500 calories. 
  People of any height and hormone dominance should not go below 1000 calories 
  per day unless directed by their doctor. Calorie counting can quickly lead to 
  disordered eating and an unhealthy relationship with food -- if the majority of
  your day is focused on calories, exercise, or weight, stop following your plan
  and seek help.
</div>

## About
This site uses the equation from Mifflin MD, St Jeor ST, Hill LA, Scott BJ, Daugherty SA, Koh YO. A new predictive equation for resting energy expenditure in healthy individuals. Am J Clin Nutr. 1990;51(2):241-247. doi:10.1093/ajcn/51.2.241

BMR Categories:
 <ul>
  <li>Sedentary: little to no exercise in a day</li>
  <li>Lightly active: light exercise/sports 1-3 days/week</li>
  <li>Moderately active: moderate exercise/sports 3-5 days/week</li>
  <li>Very active: hard exercise/sports 6-7 days/week</li>
  <li>Extremely active: very hard exercise/sports and physical job or 2x training</li>
</ul>

## User Input
<p>Select measurement units:</p>
<div class="measurement-buttons" id="measurement-buttons">
<input type="radio" id="us" name="measurement" value="us" checked />
<label for="us">US (lbs and in) </label>

<input type="radio" id="metric" name="measurement" value="metric" />
<label for="metric">Metric (kg and cm) </label>
</div>

<p>Select gender (based on hormone dominance):</p>
<div class="gender-buttons" id="gender-buttons">
  <input type="radio" id="male" name="gender" value="male" />
  <label for="male">Male </label>

  <input type="radio" id="mixed" name="gender" value="mixed" checked />
  <label for="mixed">Mixed </label>

  <input type="radio" id="female" name="gender" value="female" />
  <label for="female">Female </label>
</div>

<label for="weight">Starting Weight:</label>
<input type="text" id="weight" name="weight" />

<label for="height">Height:</label>
<input type="text" id="height" name="height" />

<label for="age">Age:</label>
<input type="text" id="age" name="age" />

<label for="cal_in">Average daily calories in:</label>
<input type="text" id="calIn" name="calIn" />

<label for="adj">Calorie adjustment (added to BMR):</label>
<input type="text" id="adj" name="adj" value=0 />

<label for="weeks">Total weeks:</label>
<input type="text" id="weeks" name="weeks" value=120 />

:::

<!-- Use 'Submit' to update the plot -->
<input type='button' id='plot' value='Submit' class='btn btn-primary'>

<!-- Placeholder for the plot -->
<div id="tester" style="width:95%;height:500px;"></div>

<!-- The JS Code -->
```{js, echo=FALSE}

// Get the html element that should contain the plot
plot = document.getElementById('tester');

var bedridden = 1;
var sedentary = 1.2;
var light = 1.375;
var moderate = 1.55;
var very = 1.725;
var extreme = 1.9;

var in2cm = 2.54;
var lb2kg = 2.2;

// Get array of dates
// From https://bobbyhadz.com/blog/javascript-get-all-dates-between-two-dates
function getDatesInRange(startDate, endDate) {
  const date = new Date(startDate.getTime());

  // Exclude start date
  date.setDate(date.getDate() + 1);

  const dates = [];

  // Exclude end date
  while (date < endDate) {
    dates.push(new Date(date));
    date.setDate(date.getDate() + 7);
  }

  return dates;
}

// ------- Set up functions

// Calculate BMI
function getBMI(height, weight) {
  return weight / (height * height * 0.01 * 0.01);
};

// Equation based on: 
// Mifflin MD, St Jeor ST, Hill LA, Scott BJ, Daugherty SA, Koh YO.
// A new predictive equation for resting energy expenditure in healthy individuals.
// Am J Clin Nutr. 1990;51(2):241-247. doi:10.1093/ajcn/51.2.241

// Set the equation based on given gender
function getREE(gender, weight, height, age, calIn, adj, multiplier) {
  if ( gender === "male" ) {
    REE = (((10 * weight) + (6.25 * height) - (5 * age)) + 5 + adj) * multiplier;
  } else if ( gender === "female" ) {
    REE = (((10 * weight) + (6.25 * height) - (5 * age)) - 161 + adj) * multiplier;
  } else { // gender = "mixed"
    REE = (((10 * weight) + (6.25 * height) - (5 * age)) - 78 + adj) * multiplier;
  };
  
  // Now get the current BMI
  BMI = getBMI(height, weight);
  // Calculate caloric difference and weight change
  // Negative numbers are caloric surplus, positive numbers are caloric deficit
  // Don't go below a safe BMI!
  if (BMI <=18.60 && calIn < REE) {
  calIn = REE;
  };
  calDiff = REE - calIn;
  newWeight = weight - ((calDiff * 7) / 7700);
};

// Calculate REE
function calculateREEbyMultiplier (measurement, gender, weight, height, age, 
calIn, adj,timeframe, multiplier, arrREE, arrWeight, arrCalDiff, arrBMI) {
  for (var i = 0; i < timeframe.length; i++) {
    myweight = arrWeight[arrWeight.length - 1]
    getREE(gender, myweight, height, age, calIn, adj, multiplier);
    arrREE.push(REE);
    arrWeight.push(newWeight);
    arrCalDiff.push(calDiff);
    arrBMI.push(BMI);
  };
  // Remove final weight
  arrWeight.pop();
  // Convert US units back to lbs
  if ( measurement === "us") {
    arrWeight.forEach((value, index) => {
      arrWeight[index] *= lb2kg;
    });
  };  
};

// Calculate all of the updated values for button clicks
function calculateAllREE(measurement, gender, weight, height, age, 
  calIn, adj, timeframe,
  bedridden, arrREEBr, arrWeightBr, arrCalDiffBr, arrBMIBr, 
  sedentary, arrREESed, arrWeightSed, arrCalDiffSed, arrBMISed,
  light, arrREELt, arrWeightLt, arrCalDiffLt, arrBMILt,
  moderate, arrREEMod, arrWeightMod, arrCalDiffMod, arrBMIMod,
  very, arrREEVery, arrWeightVery, arrCalDiffVery, arrBMIVery,
  extreme, arrREEEx, arrWeightEx, arrCalDiffEx, arrBMIEx) {
  
  // Beddridden
  calculateREEbyMultiplier (measurement, gender, weight, height, age, calIn, adj, 
  timeframe, bedridden, arrREEBr, arrWeightBr, arrCalDiffBr, arrBMIBr);
  
  // Sedentary
  calculateREEbyMultiplier (measurement, gender, weight, height, age, calIn, adj, 
  timeframe, sedentary, arrREESed, arrWeightSed, arrCalDiffSed, arrBMISed);
  // Light
  calculateREEbyMultiplier (measurement, gender, weight, height, age, calIn, adj, 
  timeframe, light, arrREELt, arrWeightLt, arrCalDiffLt, arrBMILt);

  // Moderate
  calculateREEbyMultiplier (measurement, gender, weight, height, age, calIn, adj, 
  timeframe, moderate, arrREEMod, arrWeightMod, arrCalDiffMod, arrBMIMod);

  // Very
  calculateREEbyMultiplier (measurement, gender, weight, height, age, calIn, adj, 
  timeframe, very, arrREEVery, arrWeightVery, arrCalDiffVery, arrBMIVery);

  // Extreme
  calculateREEbyMultiplier (measurement, gender, weight, height, age, calIn, adj, 
  timeframe, extreme, arrREEEx, arrWeightEx, arrCalDiffEx, arrBMIEx);
  
  return arrREEBr, arrWeightBr, arrCalDiffBr, arrBMIBr, 
  arrREESed, arrWeightSed, arrCalDiffSed, arrBMISed,
  arrREELt, arrWeightLt, arrCalDiffLt, arrBMILt,
  arrREEMod, arrWeightMod, arrCalDiffMod, arrBMIMod,
  arrREEVery, arrWeightVery, arrCalDiffVery, arrBMIVery,
  arrREEEx, arrWeightEx, arrCalDiffEx, arrBMIEx;

};

// ------ Create the plots after the click!!!!
$("#plot").on("click", function(){

// Read the values
var measurement = document.querySelector('input[name="measurement"]:checked').value;
var gender = document.querySelector('input[name="gender"]:checked').value;
var height = parseInt(document.getElementById("height").value);
var weight = parseInt(document.getElementById("weight").value);
var age = parseInt(document.getElementById("age").value);
var calIn = parseInt(document.getElementById("calIn").value);
var adj = parseInt(document.getElementById("adj").value);
var numWeeks = parseInt(document.getElementById("weeks").value);

// Convert US units to kg and cm
if ( measurement === "us") {
  var height = height * in2cm
  var weight = weight / lb2kg
  var weightLabel = " (lbs)"
} else {
  var weightLabel = " (kgs)"
};

// Total number of weeks to consider
const today = new Date();
const future = new Date();
future.setDate(future.getDate() + numWeeks * 7);

// Make timeframe a variable
var timeframe = getDatesInRange(today, future);

// Create the empty arrays for each multiplier category
// Bedridden
// Initialize empty arrays
const arrREEBr = [];
const arrCalDiffBr = [];
const arrWeightBr = [];
const arrBMIBr = [];
// Add existing values to new arrays
arrWeightBr.push(weight);
arrBMIBr.push(getBMI(height, weight));
  
// Sedentary
// Initialize empty arrays
const arrREESed = [];
const arrCalDiffSed = [];
const arrWeightSed = [];
const arrBMISed = [];
// Add existing values to new arrays
arrWeightSed.push(weight);
arrBMISed.push(getBMI(height, weight));

// Light
// Initialize empty arrays
const arrREELt = [];
const arrCalDiffLt = [];
const arrWeightLt = [];
const arrBMILt = [];
// Add existing values to new arrays
arrWeightLt.push(weight);
arrBMILt.push(getBMI(height, weight));

// Mod
// Initialize empty arrays
const arrREEMod = [];
const arrCalDiffMod = [];
const arrWeightMod = [];
const arrBMIMod = [];
// Add existing values to new arrays
arrWeightMod.push(weight);
arrBMIMod.push(getBMI(height, weight));

// Very
// Initialize empty arrays
const arrREEVery = [];
const arrCalDiffVery = [];
const arrWeightVery = [];
const arrBMIVery = [];
// Add existing values to new arrays
arrWeightVery.push(weight);
arrBMIVery.push(getBMI(height, weight));
  
// Extreme
// Initialize empty arrays
const arrREEEx = [];
const arrCalDiffEx = [];
const arrWeightEx = [];
const arrBMIEx = [];
// Add existing values to new arrays
arrWeightEx.push(weight);
arrBMIEx.push(getBMI(height, weight));

calculateAllREE(measurement, gender, weight, height, age, calIn, adj, timeframe, 
  bedridden, arrREEBr, arrWeightBr, arrCalDiffBr, arrBMIBr, 
  sedentary, arrREESed, arrWeightSed, arrCalDiffSed, arrBMISed,
  light, arrREELt, arrWeightLt, arrCalDiffLt, arrBMILt,
  moderate, arrREEMod, arrWeightMod, arrCalDiffMod, arrBMIMod,
  very, arrREEVery, arrWeightVery, arrCalDiffVery, arrBMIVery,
  extreme, arrREEEx, arrWeightEx, arrCalDiffEx, arrBMIEx);

// Use date only (remove irrelevant time)
timeframe = timeframe.map((x) => x.toLocaleDateString())

// =========== Finally start ploting! ===========
// Create an object with the default data
// Use the Paul Tol vibrant colors https://personal.sron.nl/~pault/

Plotly.newPlot(plot, {
  data: [
    {
      x: timeframe,
      y: arrWeightBr,
      type: "scatter",
      xaxis: "x",
      yaxis: "y",
      name: "Bedridden",
      marker: {color: '#ee3377'}
    },
    {
      x: timeframe,
      y: arrWeightSed,
      type: "scatter",
      xaxis: "x",
      yaxis: "y",
      name: "Sedentary",
      marker: {color: '#cc3311'}
    },
    {
      x: timeframe,
      y: arrWeightLt,
      type: "scatter",
      xaxis: "x",
      yaxis: "y",
      name: "Lightly Active",
      marker: {color: '#ee7733'}
    },
    {
      x: timeframe,
      y: arrWeightMod,
      type: "scatter",
      xaxis: "x",
      yaxis: "y",
      name: "Moderately Active",
      marker: {color: '#009988'}
    },
    {
      x: timeframe,
      y: arrWeightVery,
      type: "scatter",
      xaxis: "x",
      yaxis: "y",
      name: "Very Active",
      marker: {color: '#33bbee'}
    },
    {
      x: timeframe,
      y: arrWeightEx,
      type: "scatter",
      xaxis: "x",
      yaxis: "y",
      name: "Extremely Active",
      marker: {color: '#0077BB'}
    },
    // Line marking healthy BMI category (min)
    {
      x: [timeframe[0], timeframe[timeframe.length-1]],
      y: [18.5, 18.5],
      type: "scatter",
      xaxis: "x",
      yaxis: "y2",
      name: "Healthy BMI Range",
      marker: {color: '#d3d3d3'}
    },
    // Line marking healthy BMI category (max)
    {
      x: [timeframe[0], timeframe[timeframe.length-1]],
      y: [25, 25],
      type: "scatter",
      xaxis: "x",
      yaxis: "y2",
      name: "Healthy BMI Range",
      showlegend: false,
      marker: {color: '#d3d3d3'}
    },
    {
      x: timeframe,
      y: arrBMIBr,
      type: "scatter",
      xaxis: "x",
      yaxis: "y2",
      name: "Bedridden BMI",
      showlegend: false,
      marker: {color: '#ee3377'}
    },
    {
      x: timeframe,
      y: arrBMISed,
      type: "scatter",
      xaxis: "x",
      yaxis: "y2",
      name: "Sedentary BMI",
      showlegend: false,
      marker: {color: '#cc3311'}
    },
    {
      x: timeframe,
      y: arrBMILt,
      type: "scatter",
      xaxis: "x",
      yaxis: "y2",
      name: "Lightly Active BMI",
      showlegend: false,
      marker: {color: '#ee7733'}
    },
    {
      x: timeframe,
      y: arrBMIMod,
      type: "scatter",
      xaxis: "x",
      yaxis: "y2",
      name: "Moderately Active BMI",
      showlegend: false,
      marker: {color: '#009988'}
    },
    {
      x: timeframe,
      y: arrBMIVery,
      type: "scatter",
      xaxis: "x",
      yaxis: "y2",
      name: "Very Active BMI",
      showlegend: false,
      marker: {color: '#33bbee'}
    },
    {
      x: timeframe,
      y: arrBMIEx,
      type: "scatter",
      xaxis: "x",
      yaxis: "y2",
      name: "Extremely Active BMI",
      showlegend: false,
      marker: {color: '#0077BB'}
    },
  ],

  layout: {
    grid: {rows: 2, columns: 1, roworder: "top to bottom"},
    yaxis: { title: ('Weight'+ weightLabel) },
    yaxis2: { anchor: "x2", title: "BMI (kg/m<sup>2</sup>)" },
  }
});

// Work on a table now!
const maxSize = Math.max(timeframe.length, 
  arrWeightBr.length, arrBMIBr.length, arrREEBr.length, arrCalDiffBr.length,
  arrWeightSed.length, arrBMISed.length, arrREESed.length, arrCalDiffSed.length,
  arrWeightLt.length, arrBMILt.length, arrREELt.length, arrCalDiffLt.length,
  arrWeightMod.length, arrBMIMod.length, arrREEMod.length, arrCalDiffMod.length,
  arrWeightVery.length,  arrBMIVery.length, arrREEVery.length,
  arrCalDiffVery.length,
  arrWeightEx.length, arrBMIEx.length, arrREEEx.length, arrCalDiffEx.length,
 );

for (let i = 0; i < maxSize; i++) {
  let row = $('<tr>');
  row.append($('<td>').html(i));
  row.append($('<td>').html(timeframe[i]));
  // Bedridden
  row.append($('<td>').html(arrWeightBr[i].toFixed(1)));
  row.append($('<td>').html(arrBMIBr[i].toFixed(1)));
  row.append($('<td>').html(arrREEBr[i].toFixed(0)));
  row.append($('<td>').html(arrCalDiffBr[i].toFixed(0)));
  // Sedentary
  row.append($('<td>').html(arrWeightSed[i].toFixed(1)));
  row.append($('<td>').html(arrBMISed[i].toFixed(1)));
  row.append($('<td>').html(arrREESed[i].toFixed(0)));
  row.append($('<td>').html(arrCalDiffSed[i].toFixed(0)));
  // Light
  row.append($('<td>').html(arrWeightLt[i].toFixed(1)));
  row.append($('<td>').html(arrBMILt[i].toFixed(1)));
  row.append($('<td>').html(arrREELt[i].toFixed(0)));
  row.append($('<td>').html(arrCalDiffLt[i].toFixed(0)));
  // Mod
  row.append($('<td>').html(arrWeightMod[i].toFixed(1)));
  row.append($('<td>').html(arrBMIMod[i].toFixed(1)));
  row.append($('<td>').html(arrREEMod[i].toFixed(0)));
  row.append($('<td>').html(arrCalDiffMod[i].toFixed(0)));
  // Very
  row.append($('<td>').html(arrWeightVery[i].toFixed(1)));
  row.append($('<td>').html(arrBMIVery[i].toFixed(1)));
  row.append($('<td>').html(arrREEVery[i].toFixed(0)));
  row.append($('<td>').html(arrCalDiffVery[i].toFixed(0)));
  // Extreme
  row.append($('<td>').html(arrWeightEx[i].toFixed(1)));
  row.append($('<td>').html(arrBMIEx[i].toFixed(1)));
  row.append($('<td>').html(arrREEEx[i].toFixed(0)));
  row.append($('<td>').html(arrCalDiffEx[i].toFixed(0)));
  
  $('#table-content').append(row);
};

})
```

<!-- Use 'Submit' to update the plot -->
<br>
<center>
<input type='button' id='showtable' value='Toggle Table' class='btn btn-primary'>
</center>

<!-- Placeholder for the table -->
<div id="table-test" style="width:95%;">
  <table id="progress-table">
    <thead>
      <tr>
        <th rowspan="2" width="15%">Week</th>
        <th rowspan="2" width="15%">Date</th>
        <th colspan="4">Bedridden</th>
        <th colspan="4">Sedentary</th>
        <th colspan="4">Lightly Active</th>
        <th colspan="4">Moderately Active</th>
        <th colspan="4">Very Active</th>
        <th colspan="4">Extremely Active</th>
      </tr>
      <tr>
        <!-- Bedridden -->
        <th scope="col">Weight</th>
        <th scope="col">BMI</th>
        <th scope="col">Calories Used</th>
        <th scope="col">Calorie Difference</th>
        <!-- Sedentary -->
        <th scope="col">Weight</th>
        <th scope="col">BMI</th>
        <th scope="col">Calories Used</th>
        <th scope="col">Calorie Difference</th>
        <!-- Light -->
        <th scope="col">Weight</th>
        <th scope="col">BMI</th>
        <th scope="col">Calories Used</th>
        <th scope="col">Calorie Difference</th>
        <!-- Mod -->
        <th scope="col">Weight</th>
        <th scope="col">BMI</th>
        <th scope="col">Calories Used</th>
        <th scope="col">Calorie Difference</th>
        <!-- Very -->
        <th scope="col">Weight</th>
        <th scope="col">BMI</th>
        <th scope="col">Calories Used</th>
        <th scope="col">Calorie Difference</th>
        <!-- Extreme -->
        <th scope="col">Weight</th>
        <th scope="col">BMI</th>
        <th scope="col">Calories Used</th>
        <th scope="col">Calorie Difference</th>
      </tr>
    </thead>
    <tbody id="table-content">
    </tbody>
  </table>
</div>

```{js, echo=FALSE}
// Start by creating the table
// Consider following this in the future https://datatables.net/forums/discussion/68846/is-there-a-way-to-toggle-the-colvisgroup-button
$('#progress-table').DataTable({ 
  "aLengthMenu": [[25, 50, 75, -1], [25, 50, 75, "All"]],
  "pageLength": 25,
  stateSave: true,
  "bDestroy": true,
  layout: {
        topStart: {
            buttons: [
              {
                extend: 'colvisGroup',
                    text: 'Bedridden',
                    name: 'Bedridden',
                    // 0 is Week index, always want to show
                    show: [1, 2, 3, 4, 5],
                    hide: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
                           19, 20, 21, 22, 23, 24, 25],
                },
                                {
                extend: 'colvisGroup',
                    text: 'Sedentary',
                    show: [1, 6, 7, 8, 9],
                    hide: [2, 3, 4, 5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
                },
                {
                extend: 'colvisGroup',
                    text: 'Lightly Active',
                    show: [1, 10, 11, 12, 13],
                    hide: [2, 3, 4, 5, 6, 7, 8, 9, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
                },
                {
                extend: 'colvisGroup',
                    text: 'Moderately Active',
                    show: [1, 14, 15, 16, 17],
                    hide: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 18, 19, 20, 21, 22, 23, 24, 25]
                },
                {
                extend: 'colvisGroup',
                    text: 'Very Active',
                    show: [1, 18, 19, 20, 21],
                    hide: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 22, 23, 24, 25]
                },
                {
                extend: 'colvisGroup',
                    text: 'Extremely Active',
                    show: [1, 22, 23, 24, 25],
                    hide: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
                },
                {
                    extend: 'colvisGroup',
                    text: 'Show all',
                    show: ':hidden'
                }
            ]
        }
    }
  });

// Now toggle the Table on and off
$("#showtable").on("click", function(){
  var x = document.getElementById("table-test");
  if (x.style.display === "none") {
    x.style.display = "flex";
  } else {
    x.style.display = "none";
  };
});
```